baseURL = "https://dadascience.design/"
languageCode = "en"
defaultContentLanguage = "en"
title = "fubits@git"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-even"
relativeurls = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.csv$", "\\.rda$", "\\.tif$", "\\.rds$",]

publishDir = "../ellocke.github.io/"

preserveTaxonomyNames = true
hasCJKLanguage = false     # has chinese/japanese/korean ?
paginate = 5
copyright = ""            # default: author.name ↓

[author]                  # essential
  name = "Ilja @fubits"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 20
  identifier = "posts"
  url = "/post/"
#[[menu.main]]
#  name = "Topics"
#  weight = 30
#  identifier = "topics"
#  url = "/topics/"
#[[menu.main]]
#  name = "Categories"
#  weight = 30
#  identifier = "categories"
#  url = "/categories/"
[[menu.main]]
  name = "Topics"
  weight = 35
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 0
  identifier = "about"
  url = "/about/"

[params]
  highlightjsVersion = "9.11.0"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "magula"
  version = "4.x"           # Used to give a friendly message when you have an incompatible update

  since = "2018"            # Site creation time

  # site info (optional)
  logoTitle = ""        # default: the title value
  keywords = ["Computational Social Science", "DataViz", "Rstats", "SciComm", "Open Science", "FOSS", "Replication"]
  description = "@fubits GitHub Page made with R, Blogdown, and Hugo theme even"

  # paginate of archives, tags and categories
  archivePaginate = 10

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = true
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ["custom.css"]
  customJS = ["highlight.pack.js", "custom.js"]

   [params.social]
    c-twitter = "https://www.twitter.com/fubits/"
    g-github = "https://www.github.com/ellocke/"
   # m-instagram = "https://keybase.com/fubits"
